// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _event_table_weight{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const f64 * k1, const f64 * k2);
  const size_t sizes[2];

  f64 * key;
  u32 * method;
  icy_mem * key_area;
  icy_mem * method_area;
}event_table_weight;

event_table_weight * event_table_weight_create(const char * optional_name);
void event_table_weight_set(event_table_weight * table, f64 key, u32 method);
void event_table_weight_insert(event_table_weight * table, f64 * key, u32 * method, size_t count);
void event_table_weight_lookup(event_table_weight * table, f64 * keys, size_t * out_indexes, size_t count);
void event_table_weight_remove(event_table_weight * table, f64 * keys, size_t key_count);
void event_table_weight_clear(event_table_weight * table);
void event_table_weight_unset(event_table_weight * table, f64 key);
bool event_table_weight_try_get(event_table_weight * table, f64 * key, u32 * method);
void event_table_weight_print(event_table_weight * table);
size_t event_table_weight_iter(event_table_weight * table, f64 * keys, size_t keycnt, f64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
