// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _intern_string_vector_2{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u128 * k1, const u128 * k2);
  const size_t sizes[2];

  u128 * key;
  u32 * value;
  icy_mem * key_area;
  icy_mem * value_area;
}intern_string_vector_2;

intern_string_vector_2 * intern_string_vector_2_create(const char * optional_name);
void intern_string_vector_2_set(intern_string_vector_2 * table, u128 key, u32 value);
void intern_string_vector_2_insert(intern_string_vector_2 * table, u128 * key, u32 * value, size_t count);
void intern_string_vector_2_lookup(intern_string_vector_2 * table, u128 * keys, size_t * out_indexes, size_t count);
void intern_string_vector_2_remove(intern_string_vector_2 * table, u128 * keys, size_t key_count);
void intern_string_vector_2_clear(intern_string_vector_2 * table);
void intern_string_vector_2_unset(intern_string_vector_2 * table, u128 key);
bool intern_string_vector_2_try_get(intern_string_vector_2 * table, u128 * key, u32 * value);
void intern_string_vector_2_print(intern_string_vector_2 * table);
size_t intern_string_vector_2_iter(intern_string_vector_2 * table, u128 * keys, size_t keycnt, u128 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
