// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _method_table{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u32 * k1, const u32 * k2);
  const size_t sizes[2];

  u32 * id;
  method_ptr * method;
  icy_mem * id_area;
  icy_mem * method_area;
}method_table;

method_table * method_table_create(const char * optional_name);
void method_table_set(method_table * table, u32 id, method_ptr method);
void method_table_insert(method_table * table, u32 * id, method_ptr * method, size_t count);
void method_table_lookup(method_table * table, u32 * keys, size_t * out_indexes, size_t count);
void method_table_remove(method_table * table, u32 * keys, size_t key_count);
void method_table_clear(method_table * table);
void method_table_unset(method_table * table, u32 key);
bool method_table_try_get(method_table * table, u32 * id, method_ptr * method);
void method_table_print(method_table * table);
size_t method_table_iter(method_table * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
