// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

string_vector_internal * string_vector_internal_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"string_id", (char *)"data"};
  static const char * const column_types[] = {"u32", "string_vector_chunk"};

  string_vector_internal * instance = calloc(sizeof(string_vector_internal), 1);
  unsigned int sizes[] = {sizeof(u32), sizeof(string_vector_chunk)};
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = 2;
  for(unsigned int i = 0; i < 2; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


string_vector_internal_index string_vector_internal_alloc(string_vector_internal * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  string_vector_internal_index index;
  index.index = idx.index;
  return index;
}

string_vector_internal_indexes string_vector_internal_alloc_sequence(string_vector_internal * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  string_vector_internal_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void string_vector_internal_remove(string_vector_internal * table, string_vector_internal_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void string_vector_internal_remove_sequence(string_vector_internal * table, string_vector_internal_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void string_vector_internal_clear(string_vector_internal * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void string_vector_internal_optimize(string_vector_internal * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void string_vector_internal_destroy(string_vector_internal ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
