// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

string_vector_defer * string_vector_defer_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"int_id"};
  static const char * const column_types[] = {"string_vector_internal_indexes"};

  string_vector_defer * instance = calloc(sizeof(string_vector_defer), 1);
  unsigned int sizes[] = {sizeof(string_vector_internal_indexes)};
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = 1;
  for(unsigned int i = 0; i < 1; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


string_vector_defer_index string_vector_defer_alloc(string_vector_defer * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  string_vector_defer_index index;
  index.index = idx.index;
  return index;
}

string_vector_defer_indexes string_vector_defer_alloc_sequence(string_vector_defer * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  string_vector_defer_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void string_vector_defer_remove(string_vector_defer * table, string_vector_defer_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void string_vector_defer_remove_sequence(string_vector_defer * table, string_vector_defer_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void string_vector_defer_clear(string_vector_defer * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void string_vector_defer_optimize(string_vector_defer * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void string_vector_defer_destroy(string_vector_defer ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
