// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _string_vector_internal{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[2];
  
  u32 * string_id;
  string_vector_chunk * data;
  icy_mem * string_id_area;
  icy_mem * data_area;
}string_vector_internal;

// a vector index.
typedef struct{
  size_t index;
}string_vector_internal_index;

typedef struct{
  size_t index;
  size_t count;
}string_vector_internal_indexes;

string_vector_internal * string_vector_internal_create(const char * optional_name);
string_vector_internal_index string_vector_internal_alloc(string_vector_internal * table);
string_vector_internal_indexes string_vector_internal_alloc_sequence(string_vector_internal * table, size_t count);
void string_vector_internal_remove(string_vector_internal * table, string_vector_internal_index index);
void string_vector_internal_remove_sequence(string_vector_internal * table, string_vector_internal_indexes * indexes);
void string_vector_internal_clear(string_vector_internal * table);
void string_vector_internal_optimize(string_vector_internal * table);
void string_vector_internal_destroy(string_vector_internal ** table);
